### ISSUE TITLE
Project Plan

### ISSUE THREAD

**Issue by dduckenfieldlopez24** [stat231-f21/blog_facts-and-stats#1]
Incarceration Rates in the United States Over Time

For our blog project we have decided to start over with a completely different topic: mass incarceration in the United States. We’re looking to track changes of incarceration rates over time across the United States all the way down to the county level. Through this, we hope to tell a story of this relatively recent phenomenon. So far we have come across datasets in .csv format from the Bureau of Justice Statistics and the Vera Project that provide all the information we will need to display the data spatially using the maps package.

For our final product we plan on having a map similar to the one made by the Vera Project that shows different data about jail and prison incarceration rates at the state and county levels. We would include our own variables of interest such as the incarceration rates for different races. This map will allow users to adjust what data they would like to look at. We would also include a time series that would show changes of incarceration rates over time. This would be part of a Shiny App that will also include other visualizations such as a table and a bar graph.

Work Timeline

Wrangling data checkpoint on November 5
Wrangle data by November 9
At least one visualization by November 12
Rough draft of all visualizations by November 16
A working draft of visualizations by November 19
Final edits by November 30

Links

Bureau of Justice Statistics
https://bjs.ojp.gov/

Vera Project
http://trends.vera.org/incarceration-rates?data=pretrial)

**Comment by bebailey** [comment]
Cool!

This was not part of the requirement, but please make sure you discuss amongst yourselves exactly how you plan to divide up the work. Perhaps it would be useful to write it down as a sort of group contract, even. To the degree possible, we want equitable contributions to the core components of the blog, with flexibility for any individual to go "above and beyond" on any particular aspect of interest to them. 

---

To embed a shiny app, you can use a code chunk (see [this link](https://bookdown.org/yihui/bookdown/web-pages-and-shiny-apps.html) for details):

```
knitr::include_app("https://your-account.shinyapps.io/your-app/", height = "600px")
```

**Comment by skyewu0** [comment]
Project Update 1:
We are on schedule. We finished most data import, wrangling, and divided up the work. Diego is going to start creating static maps that show incarceration rates in each county. Both Alex and Skye are going to create interactive maps using the leaflet package that tracks incarceration rates on a county level as well.

**Comment by skyewu0** [comment]
Project Update 2:
We are a little behind schedule since we haven't finalized our visualizations so we haven't had that much progress on writing up our blog.
But we did achieve some significant progress so far. Diego has created a static map that shows jail incarceration rate on a state level and is currently making time-series graphs to demonstrate trends throughout 1970 and 2018.
Skye has made interactive maps using Leaflet that show jail incarceration rate on a county level and implemented pop-up legends and hovering effects. She's currently working up implementing the maps onto a shiny app in which  maps that shows county-level incarceration rate will change over time (1970-2018).
